# Site settings
title: 
header-img: img/home-bg.png
email: cedcn-9mail@yahoo.com
copyright_name: cedricn8
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cedricn8
learn_profile: cedricn8
email_username: cedcn-9mail@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
